### ISSUE TITLE
Syllable markers for written word

### ISSUE THREAD

**Issue by jacobSingh** [timmahrt/pysle#5]
Hello!

Firstly, thank you so much for your hard work on this.  I'm working on a project to try and make reading more accessible, and your ISLE dictionary interface is a huge help.  What I'm trying to do is visually tie together the pronunciation with the letters it stems from.

Unfortunately, this is pretty tricky in English, particularly at the phonetic level.  I assume it is quite doable at the syllabic level. 

I found the MOBY hyphenator project, and it seems I could merge the two dictionaries, however it is inconsistent with ISLE, for instance:

> eve¥ry¥day
> everyday(jj) # ˈɛ̃ . v ɹ i . d ˌei #

In addition, it seems to be missing some very basic words like:

```
$ grep -E '^ha[\^rd]+en' mhyph.txt | head -n1
hard^en
$ grep -E '^ha[\^rd]+er' mhyph.txt | head -n1
$
```

Any ideas on how to go about this?

Thanks!
Jacob

**Comment by timmahrt** [comment]
Hi Jacob,

> I found the MOBY hyphenator project, and it seems I could merge the two dictionaries, however it is inconsistent with ISLE, for instance:

First off, the MOBY pronunciation is wrong.  You can't have two vowels separated by a consonant in a word ('eve').  Unless they're saying that should be pronounced like the name "Eve" [iv].  

Second, words generally can be resyllabified in many ways.  [e.vri] and [e.vr.i] are both acceptable pronunciations of 'every' to me.  ISLE actually has two pronunciations of 'everyday'.  In this case, if I were using a strictly automatic process to merge the MOBY and ISLE dictionaries, I'd add 'eve.ry.day' as a third pronunciation.  Does that make sense?  Basically all novel pronunciations get added as a new pronunciation.  

> In addition, it seems to be missing some very basic words like: 'harder'  Any ideas on how to go about this?

Is this a problem?  Couldn't you merge all words that appear in either MOBY or ISLE to create a unique word list?  I don't see why a given word would need to appear in both.  ISLE is 100,000 lines longer than MOBY, so I guess there are a lot of words in ISLE that are not in MOBY.

<hr>
If you want to merge ISLE and pysle in a way that pysle can use, it could be something like this:
Step 1: Get the word by replacing '¥' with the empty string ''.  Add '() # %s #' to the end of the word.
Step 2: Get the syllables by replacing '¥' with '.' and replace ' ' with '#'
Step 3: Insert the syllable string into the word string
Step 4: Append it to the end of a list of isle words

After doing this for each word, sort() on the list and then output.  Thoughts?  Have I completely missed what you are trying to do?

<hr>
Also, you seem to be using an old version of the ISLE library.  English doesn't have nasalized ɛ̃ although it appears in the example you posted.  This issue was fixed in the ISLE dictionary recently.  You should download the new one:
http://isle.illinois.edu/sst/data/g2ps/English/ISLEdict.txt

**Comment by jacobSingh** [comment]
Hi Tim,

Thanks for the thorough and quick response!  I can absolutely parse and merge the lists, that's no problem.  But the issue is, I want the user to be able to pick any common English word (even the top 10k would be sufficient since this is for kids) and get both the IPA and the written syllabic breakdown that corresponds to it.

I'm guessing from your response that no such resource exists?

Best,
J

**Comment by timmahrt** [comment]
Ah!  I misunderstood.  Now I understand what you're trying to do.  No such resource exists to my knowledge, but pysle can make a close approximation.  The function pronunciationtools.findBestSyllabification() can be used to map from an actual pronunciation to a dictionary pronunciation (for example, if someone misprounounced a word, pronounced the word with a different dialect, or slurred their pronunciation ,etc).  In this case, the "actual pronunciation" is the word spelling.  This has some problems--in particular when letters are silent or when two letters represent one sound, etc.  There is room for improvement but I think its a good approximation.  The output looks like this:  Thoughts?

```
havrilla,hav.ri.lla,hˌæv.ɹˈɪ.lə
havron,hav.ron,hˈæv.ɹn̩
haw,haw,hˈɔ
hawaii,ha.wai.i,hə.wˈɑɪ.i
```

Also, in writing this code, I found a bug in findBestSyllabification().  If you want to run the code below I recommend upgrading:

`pip install psyle --upgrade`

Here is the code:
https://www.dropbox.com/s/npbw1z5lgyqe22p/chunkWordsIntoSyllables.py?dl=0

And here is the output [~6MB large]:
https://www.dropbox.com/s/6rpxngjgsffiqk8/syllabifiedText.txt?dl=0

**Comment by timmahrt** [comment]
I found some more bugs.  They've been squashed.  I also improved the script:
https://www.dropbox.com/s/7ssopiolncisaup/chunkWordsIntoSyllables_v2.py?dl=0

The output is less generous than before--lost about 0.5MB--but there are less errors in the output.  I suspect there may be a few more bugs lying around but I need to work on other stuff at the moment.

**Comment by jacobSingh** [comment]
Awesome. Thanks! I'm working on debugging another part of the application but will test this out soon and let you know.

**Comment by jacobSingh** [comment]
Hi Tim,

So we built our prototype, and I was testing it out and came across the word "laugh"... and for some reason, it is not in the dictionary you posted here.

Any idea why?

Thanks!
Jacob

**Comment by timmahrt** [comment]
Hi Jacob,
'Laugh' is in the dictionary--line 145723.  Can you confirm that the dictionary file you have is missing that line?

I do distribute a version of the ISLE dict just for testing--it only has a few lines in it.  If you were using that, then I am not surprised you encountered this problem.

If you need a fresh copy of the ISLEdict you can get it here:
http://isle.illinois.edu/sst/data/g2ps/English/ISLEdict.txt

I tested my code with the ISLEdict and was able to retrieve the word "laugh".  If you have the latest code and 'laugh' is in the dictionary--are you encountering an exception with a stack trace that you could share?  Maybe there is a bug in the code that makes it seem 'laugh' is not there.

Thanks,
Tim

**Comment by timmahrt** [comment]
Here is a minimal example that works for me

from pysle import isletool
isleDict = isletool.LexicalTool('ISLEdict.txt')  # Where ISLEdict.txt is in the same folder as this code file
lookupResults = isleDict.lookup('laugh')
print(lookupResults)
